name: Unit Tests

on:
    workflow_dispatch:

jobs:
    build-container:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build docker
              working-directory: .
              run: docker-compose up --build app
                
